package com.dilkw.studycodekotlin.systemBars

import android.view.View

enum class SystemUIEnum(property: String, value: Int) {

    SYSTEM_UI_FLAG_VISIBLE("SYSTEM_UI_FLAG_VISIBLE", View.SYSTEM_UI_FLAG_VISIBLE),
    INVISIBLE("INVISIBLE",View.INVISIBLE),
    SYSTEM_UI_FLAG_FULLSCREEN("SYSTEM_UI_FLAG_FULLSCREEN",View.SYSTEM_UI_FLAG_FULLSCREEN),
    SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION("SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION",View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION),
    SYSTEM_UI_LAYOUT_FLAGS("SYSTEM_UI_LAYOUT_FLAGS",View.SYSTEM_UI_LAYOUT_FLAGS),
    SYSTEM_UI_FLAG_HIDE_NAVIGATION("SYSTEM_UI_FLAG_HIDE_NAVIGATION",View.SYSTEM_UI_FLAG_HIDE_NAVIGATION),
    SYSTEM_UI_FLAG_LOW_PROFILE("SYSTEM_UI_FLAG_LOW_PROFILE",View.SYSTEM_UI_FLAG_LOW_PROFILE),
    SYSTEM_UI_FLAG_IMMERSIVE("SYSTEM_UI_FLAG_IMMERSIVE", View.SYSTEM_UI_FLAG_IMMERSIVE),
    SYSTEM_UI_FLAG_IMMERSIVE_STICKY("SYSTEM_UI_FLAG_IMMERSIVE_STICKY", View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY),
    SYSTEM_UI_FLAG_LAYOUT_STABLE("SYSTEM_UI_FLAG_LAYOUT_STABLE", View.SYSTEM_UI_FLAG_LAYOUT_STABLE),


    SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN("SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN", View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN),
    SYSTEM_UI_FLAG_LIGHT_STATUS_BAR("SYSTEM_UI_FLAG_LIGHT_STATUS_BAR", View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR),
    SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR("SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR", View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR),
    STATUS_BAR_HIDDEN("STATUS_BAR_HIDDEN", View.STATUS_BAR_HIDDEN),
    STATUS_BAR_VISIBLE("STATUS_BAR_VISIBLE", View.STATUS_BAR_VISIBLE);

    public var property: String
    public var value: Int

    init {
        this.property = property
        this.value = value
    }

}
